spring:
  application:
    name: simulation-backend

  datasource:
    url: jdbc:mysql://localhost:3306/simulationpeds?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        '[format_sql]': true

    # 添加 Jackson 配置
    jackson:
        serialization:
            fail-on-empty-beans: false
        properties:
            hibernate:
            force-lazy-loading: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 9527

# AnyLogic模型配置
anylogic:
  model:
    dataset: "dataset/selected_cameras_20250531.xlsx"
  simulation:
    stoptime: 3600  # 默认仿真时间（秒）
